tunnel: rich-aroma-os
credentials-file: /Users/racs/.cloudflared/9d2ea366-d039-4088-b9d2-c5ff468b4501.json

ingress:
  - hostname: richaromacoffee.com
    service: http://localhost:8083
  - hostname: www.richaromacoffee.com
    service: http://localhost:8083
  - service: http_status:404